title:            Welcome to Yimin's Homepage
description:      Academic homepage of Yimin
url:              http://lowrank.github.io
signoff:          Yimin
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted."

links:
  - name:         CV
    url:          /cv
  - name:         Publications
    url:          /publications
  - name:         Activities
    url:          /activities
  - name:         Teach
    url:          /teach
  - name:         More
    url:          /more
  - name:         Blog
    url:          /blog
  - name:         Email
    url:          mailto:yiminz@uci.edu
    external:     true

highlighter:      rouge
permalink:        pretty
kramdown:
  input: GFM
